#!/bin/sh

sxhkd &
picom -CG &
$HOME/Projects/fun/polybar-collection/launch.sh
$HOME/.fehbg
thunar --daemon &

bspc monitor -d 1 2 3 4 5 6

bspc config focused_border_color "#787878"
bspc config normal_border_color "#181818"
bspc config border_width 1
bspc config window_gap 5

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a XTerm state=floating
