#!/bin/sh

sxhkd &
compton -CG &
$HOME/.config/polybar/launch.sh &
$HOME/.fehbg
#nitrogen --restore &
thunar --daemon &

bspc monitor -d 1 2 3 4 5 6

bspc config focused_border_color "#82b1ff"
bspc config normal_border_color "#212121"
bspc config border_width 1
bspc config window_gap 5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a XTerm state=floating

