#!/bin/sh

sxhkd &
picom -CG &
$HOME/polybar-collection/launch.sh
$HOME/.fehbg
thunar --daemon &

bspc monitor -d 1 2 3 4 5

bspc config focused_border_color "#458588"
bspc config normal_border_color "#282828"
bspc config border_width 1
bspc config window_gap 3

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
